export const SEO = {
  siteUrl:     'https://fenixiluminacion.com.ar',
  siteName:    'Fénix Electricidad e Iluminación',
  description: 'Luminarias, materiales eléctricos y asesoramiento experto en City Bell, La Plata. Atendemos desde 1977 — tres generaciones de familia.',
  ogImage:     'https://fenixiluminacion.com.ar/og-image.jpg',

  business: {
    name:        'Fénix Electricidad e Iluminación',
    address:     'C. Cantilo 745, City Bell, La Plata, Buenos Aires',
    streetAddress: 'Calle Cantilo 745',
    locality:    'City Bell',
    region:      'Buenos Aires',
    postalCode:  '1897',
    country:     'AR',
    phone:       '+542216007560',
    whatsapp:    '5492216007560',
    email:       'contacto@fenixiluminacion.com.ar',
    hours:       'Mo-Fr 08:00-18:00,Sa 09:00-14:00',
    hoursDisplay:'Lunes a Viernes · 8:00–18:00 / Sábado · 9:00–14:00',
    instagram:   'https://instagram.com/fenixcitybell',
    geo: { lat: -34.8917, lng: -58.0556 },
    mapsUrl:     'https://www.google.com/maps?cid=9156829281735180874',
    founded:     '1977',
  },
}
